version: '3.8'
services:
  # app service for your backend
  app:
    container_name: inventory-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'